author: "Brian Corrigan <brian at madglory.com>"
category: "data"
summary: "Take out the trash.  Provides functions to manually run the Erlang garbage collector."
home: "https://github.com/madglory/mod_garbageman/tree/master/"
url: "git@github.com:madglory/mod_garbageman.git"
